//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoThanhShopAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string QuantityPerUnit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public bool Discontinued { get; set; }
        public string ProductCode { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string MadeIn { get; set; }
        public string TradeMark { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Capacity { get; set; }
        public string GroupCode { get; set; }
        public Nullable<decimal> UnitPrice2 { get; set; }
        public string ProductCodeNew { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
